[package]
name = "leetcode"
version = "0.1.0"
authors = ["AceLan Kao <acelan@acelan.idv.tw>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
